spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pet_dev
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    show-sql: true